import { test, expect } from "@playwright/test";
test("service → standard/custom meals → payment → next month → reversal", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Add service", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Service name").fill("Amma’s Kitchen");
  await dialog.getByLabel("Payment phone").fill("9876543210");
  await dialog.getByLabel("breakfast price").fill("40");
  await dialog.getByLabel("lunch price").fill("80");
  await dialog.getByLabel("dinner price").fill("70");
  await dialog.getByRole("button", { name: "Add food service", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole("button", { name: /Friday, 2 October, 0 meals/ }).click();
  await dialog.getByLabel("lunch amount for Amma’s Kitchen").fill("85.50");
  // The controlled checkbox reflects confirmed persistence, not an optimistic click.
  await dialog.getByRole("checkbox", { name: "Amma’s Kitchen lunch taken" }).click();
  await expect(dialog.getByRole("checkbox", { name: "Amma’s Kitchen lunch taken" })).toBeChecked();
  await expect(dialog.getByRole("checkbox", { name: "Amma’s Kitchen breakfast taken" })).not.toBeChecked();
  await dialog.getByRole("button", { name: "Add a custom meal" }).click();
  await dialog.getByLabel("Custom meal name").fill("Evening snacks");
  await dialog.getByLabel("Custom meal amount").fill("25");
  await dialog.getByRole("button", { name: "Add meal", exact: true }).click();
  await expect(dialog.getByLabel("Meal name Evening snacks")).toBeVisible();
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await expect(page.getByRole("button", { name: /Friday, 2 October, 2 meals, 2 unpaid/ })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("button", { name: /Friday, 2 October, 2 meals, 2 unpaid/ })).toBeVisible();
  await page.getByRole("button", { name: "Payments", exact: true }).filter({ visible: true }).click();
  await expect(page.locator(".balance-total")).toContainText("₹110.50");
  await page.getByRole("button", { name: "Pay all outstanding", exact: true }).click();
  await expect(dialog).toContainText("₹110.50");
  await dialog.getByRole("button", { name: "Pay all outstanding", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByLabel("Select month and year")).toHaveValue("2026-11");
  await page.getByRole("button", { name: "Payments", exact: true }).filter({ visible: true }).click();
  await page.getByRole("button", { name: "Reverse", exact: true }).click();
  await dialog.getByRole("button", { name: "Reverse payment", exact: true }).click();
  await expect(page.locator(".balance-total")).toContainText("₹110.50");
  await expect(page.locator(".history-row")).toContainText("Reversed");
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflow).toBe(false);
  await page.screenshot({ path: testInfo.outputPath("payments.png"), fullPage: true });
  await page.getByRole("button", { name: /^(Meal tracker|Tracker)$/ }).filter({ visible: true }).click();
  await page.getByLabel("Select month and year").fill("2026-10");
  await page.screenshot({ path: testInfo.outputPath("calendar.png"), fullPage: true });
});

test("failed saves preserve input and can be retried", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Add service", exact: true }).click();
  const dialog = page.getByRole("dialog");
  await dialog.getByLabel("Service name").fill("Lunch box");
  await dialog.getByLabel("Payment phone").fill("9876543210");
  for (const kind of ["breakfast", "lunch", "dinner"]) await dialog.getByLabel(`${kind} price`).fill("50");
  await page.evaluate(() => sessionStorage.setItem("fail-next-save", "1"));
  await dialog.getByRole("button", { name: "Add food service", exact: true }).click();
  await expect(dialog.getByRole("alert")).toContainText("Could not save");
  await expect(dialog.getByLabel("Service name")).toHaveValue("Lunch box");
  await dialog.getByRole("button", { name: "Add food service", exact: true }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole("button", { name: /Lunch box/ })).toBeVisible();
});
